### ISSUE TITLE
Warteanzeige (Sanduhr)

### ISSUE THREAD

**Issue by gutrund** [nudelbrot/dnd#9]
Wenn man seeeeehr große Flächen füllt ist der bucketalgo richtig arsch langsam, deshalb brauchen wir ne Warteanzeige.

**Comment by nudelbrot** [comment]
es sollte nur neu gezeichnet werden, was sich tatsachlich im viewport befindet - wird das derzeit beachtet?
das ändern des fillstyles kann ja eigentlich nicht so ewig dauern, oder?
